"""Opening 2026 Novig tickets. Championship futures are not logged."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sbm.odds import decimal_to_american, implied_to_american
from sbm.schema import League, Leg, Market, Side, Ticket, TicketKind


def _id(label: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"novig-2026:{label}"))


def _stamp() -> datetime:
    return datetime(2026, 9, 1, tzinfo=UTC)


def _straight(
    *,
    label: str,
    league: League,
    week: int,
    team: str,
    opponent: str,
    stake: float,
    implied: float | None,
    result: str | None,
    profit: float | None = None,
    cashout: float | None = None,
    market: Market,
    side: Side | None = None,
    line: float | None = None,
    game_id: str | None = None,
    notes: str | None = None,
    season: int = 2026,
) -> Ticket:
    odds = implied_to_american(implied) if implied is not None else -110
    ticket = Ticket(
        ticket_id=_id(label),
        season=season,
        sportsbook="Novig",
        stake_dollars=stake,
        american_odds=odds,
        kind=TicketKind.STRAIGHT,
        legs=[
            Leg(
                league=league,
                season=season,
                week=week,
                team_or_side=team,
                game_id=game_id,
                market=market,
                side=side,
                market_line=line,
                american_odds=odds,
                opponent=opponent,
            )
        ],
        result=result,
        profit_dollars=profit,
        cashout_dollars=cashout,
        implied_prob=implied,
        placed_at=_stamp(),
        settled_at=_stamp() if result else None,
        notes=notes,
    )
    return ticket


def novig_2026_tickets() -> list[Ticket]:
    nfl = League.NFL
    cfb = League.CFB
    tickets = [
        _straight(
            label="ou-spread-mich",
            league=cfb,
            week=1,
            team="OU",
            opponent="MICH",
            stake=5.0,
            implied=0.52,
            result="loss",
            profit=-5.0,
            market=Market.SPREAD,
            line=-4.5,
            notes="Oklahoma -4.5 vs Michigan",
        ),
        _straight(
            label="osu-ml-tex",
            league=cfb,
            week=1,
            team="OSU",
            opponent="TEX",
            stake=5.0,
            implied=0.47,
            result="loss",
            profit=-5.0,
            market=Market.MONEYLINE,
        ),
        _straight(
            label="hou-plus-buf",
            league=nfl,
            week=1,
            team="HOU",
            opponent="BUF",
            stake=5.0,
            implied=0.51,
            result="loss",
            profit=-5.0,
            market=Market.SPREAD,
            line=1.5,
        ),
        _straight(
            label="gb-ml-min",
            league=nfl,
            week=1,
            team="GB",
            opponent="MIN",
            stake=5.0,
            implied=0.46,
            result="cashout",
            cashout=8.09,
            profit=3.09,
            market=Market.MONEYLINE,
            notes="Cashed when Vikings started to come back",
        ),
        _straight(
            label="kc-ml-den",
            league=nfl,
            week=1,
            team="KC",
            opponent="DEN",
            stake=5.0,
            implied=0.57,
            result="win",
            profit=3.77,
            market=Market.MONEYLINE,
        ),
        Ticket(
            ticket_id=_id("buf-allen-cook-parlay"),
            season=2026,
            sportsbook="Novig",
            stake_dollars=4.99,
            american_odds=decimal_to_american(3.57),
            kind=TicketKind.PARLAY,
            legs=[
                Leg(
                    league=nfl,
                    season=2026,
                    week=1,
                    team_or_side="BUF",
                    market=Market.MONEYLINE,
                    opponent="DET",
                ),
                Leg(
                    league=nfl,
                    season=2026,
                    week=1,
                    team_or_side="Josh Allen Anytime TD Over 0.5",
                    opponent="DET",
                ),
                Leg(
                    league=nfl,
                    season=2026,
                    week=1,
                    team_or_side="James Cook Anytime TD Over 0.5",
                    opponent="DET",
                ),
            ],
            result="win",
            profit_dollars=12.84,
            placed_at=_stamp(),
            settled_at=_stamp(),
            notes="3-leg 3.57x. Props are not auto-graded.",
        ),
        _straight(
            label="buf-spread-det",
            league=nfl,
            week=1,
            team="BUF",
            opponent="DET",
            stake=5.78,
            implied=0.50,
            result="cashout",
            cashout=8.21,
            profit=2.43,
            market=Market.SPREAD,
            line=-5.5,
            notes="Cashed when Lions started to come back",
        ),
        _straight(
            label="hou-plus-ttu",
            league=cfb,
            week=2,
            team="HOU",
            opponent="TTU",
            stake=5.0,
            implied=0.505,
            result="cashout",
            cashout=4.85,
            profit=-0.15,
            market=Market.SPREAD,
            line=7.5,
            notes="Cashed early; should have stuck it out",
        ),
        _straight(
            label="fla-ml-aub",
            league=cfb,
            week=3,
            team="FLA",
            opponent="AUB",
            stake=5.03,
            implied=0.575,
            result="win",
            profit=3.71,
            market=Market.MONEYLINE,
            game_id="cfb-401856687",
        ),
        _straight(
            label="miss-ml-lsu",
            league=cfb,
            week=3,
            team="MISS",
            opponent="LSU",
            stake=5.0,
            implied=0.40,
            result="win",
            profit=7.50,
            market=Market.MONEYLINE,
            game_id="cfb-401856688",
        ),
        Ticket(
            ticket_id=_id("pit-ne-parlay"),
            season=2026,
            sportsbook="Novig",
            stake_dollars=5.0,
            american_odds=decimal_to_american(3.43),
            kind=TicketKind.PARLAY,
            legs=[
                Leg(
                    league=nfl,
                    season=2026,
                    week=2,
                    team_or_side="PIT",
                    game_id="2026_02_PIT_NE",
                    market=Market.SPREAD,
                    side=Side.AWAY,
                    market_line=4.5,
                    opponent="NE",
                ),
                Leg(
                    league=nfl,
                    season=2026,
                    week=2,
                    team_or_side="under",
                    game_id="2026_02_PIT_NE",
                    market=Market.TOTAL,
                    side=Side.UNDER,
                    market_line=42.5,
                    opponent="NE",
                ),
            ],
            result="loss",
            profit_dollars=-5.0,
            placed_at=_stamp(),
            settled_at=_stamp(),
            notes="2-leg 3.43x",
        ),
        _straight(
            label="tb-spread-cle",
            league=nfl,
            week=2,
            team="TB",
            opponent="CLE",
            stake=5.0,
            implied=0.49,
            result="loss",
            profit=-5.0,
            market=Market.SPREAD,
            side=Side.HOME,
            line=-8.5,
            game_id="2026_02_CLE_TB",
        ),
        _straight(
            label="jax-ml-den",
            league=nfl,
            week=2,
            team="JAX",
            opponent="DEN",
            stake=5.0,
            implied=0.47,
            result="loss",
            profit=-5.0,
            market=Market.MONEYLINE,
            side=Side.AWAY,
            game_id="2026_02_JAX_DEN",
        ),
        _straight(
            label="lv-ml-lac",
            league=nfl,
            week=2,
            team="LV",
            opponent="LAC",
            stake=5.0,
            implied=0.27,
            result="win",
            profit=13.51,
            market=Market.MONEYLINE,
        ),
        _straight(
            label="ari-ml-sea",
            league=nfl,
            week=2,
            team="ARI",
            opponent="SEA",
            stake=5.0,
            implied=0.35,
            result="loss",
            profit=-5.0,
            market=Market.MONEYLINE,
        ),
        _straight(
            label="usc-ml-ore",
            league=cfb,
            week=4,
            team="USC",
            opponent="ORE",
            stake=5.0,
            implied=0.495,
            result=None,
            market=Market.MONEYLINE,
            side=Side.HOME,
            game_id="cfb-401858469",
            notes="Gut: wrong team is favored",
        ),
        _straight(
            label="iowa-ml-mich",
            league=cfb,
            week=4,
            team="IOWA",
            opponent="MICH",
            stake=5.0,
            implied=0.39,
            result=None,
            market=Market.MONEYLINE,
            side=Side.AWAY,
            game_id="cfb-401858463",
            notes="Gut: wrong team is favored",
        ),
        _straight(
            label="van-ml-aub",
            league=cfb,
            week=4,
            team="VAN",
            opponent="AUB",
            stake=5.0,
            implied=0.355,
            result=None,
            market=Market.MONEYLINE,
            side=Side.AWAY,
            game_id="cfb-401856698",
            notes="Gut: wrong team is favored",
        ),
        _straight(
            label="car-spread-cle",
            league=nfl,
            week=3,
            team="CAR",
            opponent="CLE",
            stake=5.0,
            implied=0.55,
            result=None,
            market=Market.SPREAD,
            side=Side.AWAY,
            line=-2.5,
            game_id="2026_03_CAR_CLE",
        ),
    ]
    return tickets
